### ISSUE TITLE
startup crash with the newest vrsion from curseforge

### ISSUE THREAD

**Issue by Sailren** [HxCKDMS/HxC-Link-Pads#3]
http://paste.ubuntu.com/10106228/

**Comment by karelmikie3** [comment]
looks like a file not found exception will look in to this asap

**Comment by karelmikie3** [comment]
btw sorry for the late response was sleeping :P

**Comment by karelmikie3** [comment]
just submitted a new file to curseforge will close when approved

**Comment by karelmikie3** [comment]
update approved: http://minecraft.curseforge.com/mc-mods/227603-hxclinkpads closing.
